tag_prefix = ""
ignore_merge_commits = true
branch_whitelist = ["main"]
pre_bump_hooks = [
  "cargo set-version --locked --workspace {{version}}",
]
post_bump_hooks = [
  "git push --no-verify",
  "git push origin {{version}} --no-verify",
  "cargo publish"
]

[changelog]
path = "CHANGELOG.md"
template = "remote"
remote = "github.com"
repository = "rdfox-sys"
owner = "EKGF"
authors = [
  { username = "jgeluk", signature = "Jacobus Geluk" },
]

[commit_types]
chore = { changelog_title = "Chore", omit_from_changelog = true }

[bump_profiles]
